# Generated by Django 2.2.10 on 2020-03-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200303_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ttest',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
